import type { Metadata } from 'next';
import './globals.css';
import MainNav from '@/components/main-nav';
import { scrollbar } from '@/components/customClassName';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-main bg-background text-onPrimary flex ${scrollbar}`}>
        <MainNav />
        <main className={`m-auto overflow-auto ${scrollbar}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
