import type { Metadata } from 'next';
import './globals.css';
import MainNav from '@/components/main-nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'font-main bg-background text-onPrimary flex'}>
        <MainNav />
        <main className='m-auto'>
          {children}
        </main>
      </body>
    </html>
  );
}
